chore: Update dependencies and upgrade Flutter to Dart 2.12.0

diff --git a/.github/workflows/checkout.yml b/.github/workflows/checkout.yml
--- a/.github/workflows/checkout.yml
+++ b/.github/workflows/checkout.yml
@@ -1,20 +1,21 @@
-name: Checkout
+name: CHECKOUT
 
 on:
   workflow_dispatch:
-  push:
-    branches:
-      - "master"
-      - "develop"
-      - "feature/**"
-      - "bugfix/**"
-      - "hotfix/**"
-      - "support/**"
-    paths:
-      - "lib/**.dart"
-      - "test/**.dart"
-      - "example/**.dart"
-      - "pubspec.yaml"
+  #push:
+  #  branches:
+  #    - "master"
+  #    - "develop"
+  #    - "feature/**"
+  #    - "bugfix/**"
+  #    - "hotfix/**"
+  #    - "support/**"
+  #  paths:
+  #    - ".github/workflows/*.yml"
+  #    - "lib/pubspec.yaml"
+  #    - "lib/**.dart"
+  #    - "test/**.dart"
+  #    - "example/**.dart"
   pull_request:
     branches:
       - "master"
@@ -24,68 +25,125 @@ on:
       - "hotfix/**"
       - "support/**"
     paths:
+      - ".github/workflows/*.yml"
+      - "lib/pubspec.yaml"
       - "lib/**.dart"
       - "test/**.dart"
       - "example/**.dart"
-      - "pubspec.yaml"
 
 jobs:
   checkout:
     name: "Checkout"
     runs-on: ubuntu-latest
-    container:
-      image: dart:beta
     defaults:
       run:
         working-directory: ./
+    container:
+      image: dart:stable
+    env:
+      pub-cache-name: pub
+      threshold: 95
     timeout-minutes: 10
     steps:
       - name: 🚂 Get latest code
-        uses: actions/checkout@v3
+        id: checkout
+        uses: actions/checkout@v4
         with:
-          fetch-depth: 2
+          sparse-checkout: |
+            .github
+            pubspec.yaml
+            lib
+            test
+            analysis_options.yaml
+            CHANGELOG.md
 
-      - name: 🚃 Cache pub modules
-        uses: actions/cache@v2
-        env:
-          cache-name: cache-pub-package
+      - name: 📤 Restore Pub modules
+        id: cache-pub-restore
+        uses: actions/cache/restore@v4
         with:
           path: |
-            $PWD/.pub_cache/
-          key: ${{ runner.os }}-pub-${{ env.cache-name }}-${{ hashFiles('**/pubspec.yaml') }}
+            $HOME/.pub-cache
+          key: ${{ runner.os }}-${{ env.pub-cache-name }}-${{ hashFiles('**/pubspec.yaml') }}
 
-      - name: 🗄️ Export pub cache directory
-        run: export PUB_CACHE=$PWD/.pub_cache/
-
-      - name: 👷 Install Dependencies
+      - name: 🗄️ Export Pub cache directory
+        id: export-pub-cache
         timeout-minutes: 1
         run: |
-          dart pub get
+          export PUB_CACHE=$PWD/.pub_cache/
+          export PATH="$PATH":"$HOME/.pub-cache/bin"
+          echo "${HOME}/.pub-cache/bin" >> $GITHUB_PATH
+
+      - name: 👷 Install Dependencies
+        id: install-dependencies
+        timeout-minutes: 1
+        run: |
+          apt-get update && apt-get install -y lcov
+          dart pub global activate coverage
+          dart pub get --no-example
+
+      - name: 📥 Save Pub modules
+        id: cache-pub-save
+        uses: actions/cache/save@v4
+        with:
+          path: |
+            $HOME/.pub-cache
+          key: ${{ runner.os }}-${{ env.pub-cache-name }}-${{ hashFiles('**/pubspec.yaml') }}
 
       - name: 🔎 Check format
+        id: check-format
         timeout-minutes: 1
-        run: dart format --set-exit-if-changed -l 80 -o none .
+        run: dart format --set-exit-if-changed -l 80 -o none lib/
 
       - name: 📈 Check analyzer
+        id: check-analyzer
         timeout-minutes: 1
-        run: dart analyze --fatal-infos --fatal-warnings lib
+        run: dart analyze --fatal-infos --fatal-warnings lib/
+
+      - name: 👀 Verify versions
+        id: verify-versions
+        timeout-minutes: 1
+        run: |
+          test -f pubspec.yaml && test -f CHANGELOG.md
+          version_pubspec=$(grep '^version:' pubspec.yaml | awk '{print $2}' | sed 's/[^[:print:]]//g')
+          test -n "$version_pubspec"
+          echo "Version from pubspec.yaml: '$version_pubspec'"
+          grep -q "# $version_pubspec" CHANGELOG.md || (echo "Version not found in CHANGELOG.md" >&2; exit 1)
 
       #- name: Check with pana
       #  run: dart pub global activate pana && pana --json --no-warning --line-length 80
+
       - name: 🧪 Run tests
+        id: run-tests
+        timeout-minutes: 2
         run: |
-          dart test --coverage=coverage \
-            && dart run coverage:format_coverage --lcov --in=coverage \
-            --out=coverage/lcov.info --report-on=lib
+          dart pub global run coverage:test_with_coverage -fb -o coverage -- \
+            --platform vm --compiler=kernel --coverage=coverage \
+            --reporter=github --file-reporter=json:coverage/tests.json \
+            --timeout=10m --concurrency=12 --color \
+              test/test.dart
 
-      - name: 📥 Upload coverage to Codecov
-        uses: codecov/codecov-action@v2.1.0
-        with:
-          token: ${{ secrets.CODECOV_TOKEN }}
+      - name: 🔍 Check coverage
+        id: check-coverage
+        timeout-minutes: 2
+        run: |
+          mv coverage/lcov.info coverage/lcov.base.info
+          lcov --remove coverage/lcov.base.info '*.g.dart' -o coverage/lcov.info
+          lcov --list coverage/lcov.info
+          THRESHOLD=${{ env.threshold }}
+          COVERAGE=$(lcov --summary coverage/lcov.info | grep -i 'lines\|Total:' | tail -n 1 | awk '{print $2}' | sed 's/%//')
+          echo "Coverage is $COVERAGE%"
+          echo $COVERAGE | awk '{if ($1 < 50) exit 1}'
 
-      - name: 🧮 Check Code Coverage
-        uses: VeryGoodOpenSource/very_good_coverage@v1.2.1
+      - name: 🧹 Cleanup artifacts
+        id: cleanup-artifacts
+        if: always()
+        timeout-minutes: 2
+        run: |
+          rm -rf ~/build
+
+      - name: ✨ Upload coverage to Codecov
+        id: upload-coverage
+        timeout-minutes: 2
+        uses: codecov/codecov-action@v4
         with:
-          path: coverage/lcov.info
-          min_coverage: 90
-          #exclude: '**.g.dart **.freezed.dart'
+          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
